apiVersion: apps/v1
kind: Deployment
metadata:
  name: federacion-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: federacion
  template:
    metadata:
      labels:
        app: federacion
    spec:
      containers:
      - name: federacion
        image: rafacarrascoperalta/federacion-tfg:latest
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: DB_NAME
          value: "federacion"
