apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: federacion-ingress
  annotations:
    #cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/css/.*) $1 break;
      rewrite ^(/imagen/.*) $1 break;
      rewrite ^(/.*\.php) $1 break;
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  rules:
  - host: fabgranadabaloncesto.work.gd
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: federacion-service
            port:
              number: 80
  #tls:
  #- hosts:
  #  - fabgranadabaloncesto.work.gd
  #  secretName: federacion-cert
