apiVersion: batch/v1
kind: Job
metadata:
  name: init-db-job
spec:
  template:
    spec:
      containers:
      - name: init-db
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        command: ["sh", "-c"]
        args:
          - |
            until mysql -h mysql-service -u root -p${MYSQL_ROOT_PASSWORD} -e "SELECT 1"; do
              echo "Waiting for MySQL to be ready..."
              sleep 2
            done
            mysql -h mysql -u root -p${MYSQL_ROOT_PASSWORD} < /scripts/init-db.sql
        volumeMounts:
        - name: init-db-script
          mountPath: /scripts
      restartPolicy: OnFailure
      volumes:
      - name: init-db-script
        configMap:
          name: db-init-script
