apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-script
data:
  init-db.sql: |
    CREATE DATABASE IF NOT EXISTS federacion;
    USE federacion;
    CREATE TABLE `equipos` (
      `nombre_equipo` varchar(20) NOT NULL,
      `localidad` varchar(20) NOT NULL,
      `dia_partido` text NOT NULL,
      `hora_partido` varchar(5) NOT NULL,
      `color_equipacion` varchar(15) NOT NULL,
      `lugar_partido` varchar(50) NOT NULL,
      `correo` varchar(30) NOT NULL,
      `logo` blob NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;
    INSERT INTO `equipos` (`nombre_equipo`, `localidad`, `dia_partido`, `hora_partido`, `color_equipacion`, `lugar_partido`, `correo`, `logo`) VALUES
    ('CAB ATARFE', 'ATARFE', 'Sabado', '13:00', 'VERDE', 'POLIDEPORTIVO MUNICIPAL DE ATARFE', 'atarfebaloncesto@gmail.com', 0x696d6167656e2f6174617266652e6a7067),
    ('CB AGUSTINOS', 'GRANADA', 'Sabado', '17:00', 'AMARILLO', 'COLEGIO AGUSTINOS', 'agustinosbaloncesto@gmail.com', 0x696d6167656e2f6167757374696e6f732e706e67),
    ('CB ALHOTUR', 'ALHENDIN', 'Domingo', '12:30', 'MORADO', 'PABELLON MUNICIPAL DE ALHENDIN', 'alhoturbaloncesto@gmail.com', 0x696d6167656e2f616c686f7475722e6a7067),
    ('CB FUNDACION', 'GRANADA', 'Sabado', '21:00', 'ROJO', 'PABELLON VELETA', 'fundacionbaloncesto@gmail.com', 0x696d6167656e2f66756e646163696f6e2e6a7067),
    ('CB RACA', 'GRANADA', 'Domingo', '12:00', 'GRIS', 'COLEGIO RAMON Y CAJAL', 'racabaloncesto@gmail.com', 0x696d6167656e2f726163612e6a7067),
    ('CB SANTA FE', 'SANTA FE', 'Sabado', '19:00', 'AZUL', 'POLIDEPORTIVO MUNICIPAL DE SANTA FE', 'baloncestosantafe@gmail.com', 0x696d6167656e2f73616e74615f66652e706e67);
    CREATE TABLE `jugadores` (
      `dni` varchar(9) NOT NULL,
      `nombre_equipo` varchar(20) NOT NULL,
      `nombre` varchar(20) NOT NULL,
      `apellidos` varchar(40) NOT NULL,
      `fecha_nacimiento` varchar(10) NOT NULL,
      `posicion` varchar(10) NOT NULL,
      `dorsal` tinyint(2) NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;
    INSERT INTO `jugadores` (`dni`, `nombre_equipo`, `nombre`, `apellidos`, `fecha_nacimiento`, `posicion`, `dorsal`) VALUES
    ('22222222A', 'CAB ATARFE', 'ALEJANDRO', 'CARMONA RODRIGUEZ', '2002-06-14', 'Escolta', 30),
    ('22222222B', 'CAB ATARFE', 'GUSTAVO', 'HERRERA RIVERA', '2002-07-24', 'Base', 15),
    ('22222222C', 'CAB ATARFE', 'MIGUEL', 'CERVILLA GALLEGO', '2001-02-24', 'Escolta', 25),
    ('22222222D', 'CAB ATARFE', 'JORGE', 'MARTINEZ OCAÑA', '2000-10-29', 'Ala-Pivot', 40),
    ('22222222E', 'CAB ATARFE', 'JOAQUIN', 'PRIETO BLANCO', '1998-01-09', 'Pivot', 12),
    ('33333333A', 'CB ALHOTUR', 'MARC', 'BERMUDA CUESTA', '1996-04-02', 'Alero', 6),
    ('33333333B', 'CB ALHOTUR', 'MANUEL', 'RAMIREZ CARA', '1986-06-22', 'Base', 1),
    ('33333333C', 'CB ALHOTUR', 'PABLO', 'ROCERO DOCE', '1982-02-27', 'Escolta', 27),
    ('33333333D', 'CB ALHOTUR', 'ALVARO', 'PINTOR  CARMONA', '1999-07-17', 'Ala-Pivot', 13),
    ('33333333E', 'CB ALHOTUR', 'JESUS', 'FERNANDEZ HERNANDEZ', '1985-11-03', 'Pivot', 31),
    ('44444444A', 'CB AGUSTINOS', 'DAVID', 'LOPEZ GONZALEZ', '2003-04-23', 'Base', 16),
    ('44444444B', 'CB AGUSTINOS', 'ALVARO', 'GONZALEZ MAYA', '2001-05-17', 'Alero', 0),
    ('44444444C', 'CB AGUSTINOS', 'CURRO', 'CUENCA FRANCO', '2001-12-02', 'Escolta', 45),
    ('44444444D', 'CB AGUSTINOS', 'VICTOR', 'BENITEZ BLAYA', '2002-01-22', 'Ala-Pivot', 30),
    ('44444444E', 'CB AGUSTINOS', 'MANUEL', 'ROMERO JIMENEZ', '2004-05-10', 'Pivot', 8),
    ('55555555A', 'CB FUNDACION', 'JAIME', 'ALVAREZ', '1998-07-12', 'Base', 2),
    ('55555555B', 'CB FUNDACION', 'JESUS', 'TORRENTE CHAMORRO', '1999-03-28', 'Escolta', 4),
    ('55555555C', 'CB FUNDACION', 'JOAN', 'MARCH ORTIZ', '1991-09-11', 'Alero', 17),
    ('55555555D', 'CB FUNDACION', 'PABLO', 'LAFUENTE PALMA', '2000-06-19', 'Ala-Pivot', 65),
    ('55555555E', 'CB FUNDACION', 'FABIO', 'TESO PEREZ', '2002-12-29', 'Pivot', 16),
    ('66666666A', 'CB RACA', 'ALEJANDRO', 'ROSADO RIOS', '1988-12-09', 'Base', 7),
    ('66666666B', 'CB RACA', 'ANGEL', 'PIMENTEL MESONES', '1996-05-03', 'Escolta', 19),
    ('66666666C', 'CB RACA', 'ANDRES', 'VALLES GAITAN', '1997-08-19', 'Escolta', 28),
    ('66666666D', 'CB RACA', 'ALVARO', 'LLORENS ESTEVEZ', '1982-04-17', 'Ala-Pivot', 26),
    ('66666666E', 'CB RACA', 'PABLO', 'VILLAR LAMORENA', '1992-09-27', 'Pivot', 9),
    ('77777777A', 'CB SANTA FE', 'GERMAN', 'SANCHEZ GONZALEZ', '1994-02-08', 'Ala-Pivot', 16),
    ('77777777B', 'CB SANTA FE', 'JERO', 'MARTINEZ QUERO', '2001-06-10', 'Base', 6),
    ('77777777C', 'CB SANTA FE', 'NOEL', 'MARTINEZ QUERO', '2004-03-15', 'Escolta', 66),
    ('77777777D', 'CB SANTA FE', 'RAUL', 'MERINO GARCIA', '2002-09-25', 'Pivot', 7),
    ('77777777E', 'CB SANTA FE', 'DIEGO', 'VILLANUEVA', '2000-05-25', 'Alero', 17);
    CREATE TABLE `partidos` (
      `jornada` varchar(20) NOT NULL,
      `nombre_equipo` varchar(30) NOT NULL,
      `dia` varchar(10) NOT NULL,
      `hora` varchar(5) NOT NULL,
      `visitante` varchar(30) NOT NULL,
      `lugar` varchar(50) NOT NULL,
      `resultados` varchar(7) NOT NULL,
      `cod_partido` int(5) NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;
    INSERT INTO `partidos` (`jornada`, `nombre_equipo`, `dia`, `hora`, `visitante`, `lugar`, `resultados`, `cod_partido`) VALUES
    ('Jornada 1', 'CAB ATARFE', '2024-05-04', '13:00', 'CB AGUSTINOS', 'POLIDEPORTIVO MUNICIPAL DE ATARFE', '45 - 68', 2),
    ('Jornada 1', 'CB ALHOTUR', '2024-05-05', '12:30', 'CB RACA', 'PABELLON MUNICIPAL DE ALHOTUR', '80 - 72', 3),
    ('Jornada 1', 'CB FUNDACION', '2024-05-04', '21:00', 'CB SANTA FE', 'PABELLON VELETA', '65 - 78', 4),
    ('Jornada 2', 'CB AGUSTINOS', '2024-05-11', '17:00', 'CB ALHOTUR', 'COLEGIO AGUSTINOS', '58 - 52', 5),
    ('Jornada 2', 'CB RACA', '2024-05-12', '12:00', 'CB FUNDACION', 'COLEGIO RAMON Y CAJAL', '75 - 65', 6),
    ('Jornada 2', 'CAB ATARFE', '2024-05-11', '13:00', 'CB SANTA FE', 'POLIDEPORTIVO MUNICIPAL DE ATARFE', '67 - 45', 7),
    ('Jornada 3', 'CB ALHOTUR', '2024-05-18', '12:30', 'CB FUNDACION', 'PABELLON MUNICIPAL DE ALHOTUR', '', 8),
    ('Jornada 3', 'CAB ATARFE', '2024-05-18', '13:00', 'CB RACA', 'POLIDEPORTIVO MUNICIPAL DE ATARFE', '', 9),
    ('Jornada 3', 'CB AGUSTINOS', '2024-05-18', '17:00', 'CB SANTA FE', 'COLEGIO AGUSTINOS', '68 - 85', 10),
    ('Jornada 4', 'CB FUNDACION', '2024-05-25', '21:00', 'CB AGUSTINOS', 'PABELLON VELETA', '', 11),
    ('Jornada 4', 'CB SANTA FE', '2024-05-25', '19:00', 'CB ALHOTUR', 'POLIDEPORTIVO MUNICIPAL DE SANTA FE', '69 - 62', 12),
    ('Jornada 4', 'CAB ATARFE', '2024-05-25', '13:00', 'CB RACA', 'POLIDEPORTIVO MUNICIPAL DE ATARFE', '', 13),
    ('Jornada 5', 'CB RACA', '2024-06-01', '12:00', 'CB AGUSTINOS', 'COLEGIO RAMON Y CAJAL', '', 14),
    ('Jornada 5', 'CB SANTA FE', '2024-06-01', '19:00', 'CB FUNDACION', 'POLIDEPORTIVO MUNICIPAL DE SANTA FE', '', 15),
    ('Jornada 5', 'CB ALHOTUR', '2024-06-01', '12:30', 'CAB ATARFE', 'PABELLON MUNICIPAL DE ALHOTUR', '', 16);
    ALTER TABLE `equipos`
      ADD PRIMARY KEY (`nombre_equipo`);
    ALTER TABLE `jugadores`
      ADD PRIMARY KEY (`dni`),
      ADD KEY `nombre_equipo` (`nombre_equipo`) USING BTREE;
    ALTER TABLE `partidos`
      ADD PRIMARY KEY (`cod_partido`),
      ADD KEY `nombre_equipo` (`nombre_equipo`);
    ALTER TABLE `partidos`
      MODIFY `cod_partido` int(5) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=18;
    COMMIT;
